SELECT C.COURSENO AS 'COURSE', OFFTERM AS 'TERM', OFFLOCATION AS 'LOCATION', OFFLIMIT+5 AS 'NEWLIMIT'
FROM OFFERING O
JOIN COURSE C ON O.COURSENO = C.COURSENO
WHERE OFFYEAR = '2006'
ORDER BY OFFTERM, C.COURSENO;

SELECT CONCAT(FACLASTNAME, ' ', FACFIRSTNAME) AS 'FACNAME'
FROM FACULTY
WHERE FACSUPERVISOR IS NULL;

SELECT DISTINCT *
FROM REGISTRATION R
WHERE (REGTERM = 'WINTER' AND REGYEAR = '2006')
OR (REGTERM = 'FALL' AND REGYEAR = '2005')
ORDER BY REGYEAR, REGNO;

SELECT STDFIRSTNAME, STDLASTNAME, REGDATE, REGTERM, REGYEAR
FROM STUDENT S
JOIN REGISTRATION R ON S.STDSSN = R.STDSSN
WHERE REGSTATUS = 'F';

SELECT FACSSN, FACFIRSTNAME, FACLASTNAME
FROM FACULTY
WHERE FACDEPT = 'FIN';

SELECT FACRANK, ROUND(AVG(FACSALARY), 0) AS 'AVGSALARY'
FROM FACULTY 
WHERE FACDEPT = 'MS'
GROUP BY FACRANK
HAVING AVG(FACSALARY) < 80000;

SELECT OFFTERM, OFFYEAR, C.COURSENO, CRSDESC
FROM COURSE C
JOIN OFFERING O ON C.COURSENO = O.COURSENO
JOIN ENROLLMENT E ON O.OFFERNO = E.OFFERNO
JOIN REGISTRATION R ON E.REGNO = R.REGNO
JOIN STUDENT S ON R.STDSSN = S.STDSSN
WHERE STDFIRSTNAME = 'CANDY'
AND STDLASTNAME = 'KENDALL';

SELECT S.STDSSN, STDLASTNAME, STDFIRSTNAME, COUNT(OFFERNO) AS 'ENROLLMENTS'
FROM STUDENT S
JOIN REGISTRATION R ON S.STDSSN = R.STDSSN
JOIN ENROLLMENT E ON R.REGNO = E.REGNO
GROUP BY STDSSN
HAVING COUNT(OFFERNO) > 2
ORDER BY COUNT(OFFERNO) DESC, STDLASTNAME, STDFIRSTNAME;

SELECT STDCLASS, ROUND(AVG(STDGPA), 2) AS 'AverageGPA'
FROM STUDENT
GROUP BY STDCLASS
HAVING ROUND(AVG(STDGPA), 2) = (SELECT ROUND(MAX(AVG_GPA), 2) AS `LARGEST AVERAGE`
FROM (SELECT AVG(STDGPA) AS AVG_GPA
FROM STUDENT
GROUP BY STDCLASS) X);

SELECT STDFIRSTNAME AS 'FIRSTNAME', STDLASTNAME AS 'LASTNAME', 'Std' AS StdOrFac
FROM STUDENT S
JOIN REGISTRATION R ON S.STDSSN = R.STDSSN
WHERE REGTERM = 'WINTER' AND REGYEAR = '2006'
UNION
SELECT FACFIRSTNAME AS 'FIRSTNAME', FACLASTNAME AS 'LASTNAME', 'Fac' AS StdOrFac
FROM FACULTY F
JOIN OFFERING O ON F.FACSSN = O.FACSSN
WHERE OFFTERM = 'WINTER' AND OFFYEAR = '2006';
